### ISSUE TITLE
Create Reading List about Online Safety in Activist Tech space

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/theory-of-online-misogyny#14]
**Objective**
To compile a reading list about how to be safe online.

**Description**
Many of the people working in this space are potential targets of online harassment. The goal of this task is to build the literature so we can one day design a keep-yourself-safe guide for members of Opt Out Tools. This would be for internal use.

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [x] Create [Reading list](https://github.com/opt-out-tools/theory-of-online-misogyny/wiki/Reading-List:-Online-Safety-for-Feminnist-Tech-Activists)

**Comment by shepni** [comment]
Added the reading list to the wiki https://github.com/opt-out-tools/theory-of-online-misogyny/wiki/Reading-List:-Online-Safety-for-Feminnist-Tech-Activists
