### ISSUE TITLE
Research EU/Intl. Organisations definitions of online misogyny

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/theory-of-online-misogyny#5]
**Objective**

**Description**
see also https://github.com/opt-out-tools/theory-of-online-misogyny/issues/12

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [x] Create Wiki entry with EU definitions of online misogyny (and related terminology)
- [x] Create Wiki entry with UN definitions of online misogyny (and related terminology)

**Comment by sophielisawalker** [comment]
The No Hate Speech Campaign from the Council of Europe has several handbooks and tools which explore hate speech from a human rights angle and how to tackle it.

Adriane Van der Wilk has written extensively on the various definitions in her recent CoE report. 
https://www.europarl.europa.eu/RegData/etudes/STUD/2018/604979/IPOL_STU(2018)604979_EN.pdf

**Comment by shepni** [comment]
See EU Definitions [here](https://github.com/opt-out-tools/theory-of-online-misogyny/wiki/EU-Definitions-of-Online-Misogyny)
See UN Definitions [here](https://github.com/opt-out-tools/theory-of-online-misogyny/wiki/UN-Definitions-of-Online-Misogyny)
