### ISSUE TITLE
[WIP] Identify additional fields/actors that have defined online misogyny and need to be researched

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/theory-of-online-misogyny#6]
**Objective**

**Description**
see also https://github.com/opt-out-tools/theory-of-online-misogyny/issues/12

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

**Comment by shepni** [comment]
Civil Society definitions
Industry definitions
...
